---
- name: Install Docker and Docker Compose
  hosts: myserver_deploy_next
  become: yes
  vars:
    docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    docker_compose_version: "2.39.1"  # можно заменить на актуальную версию

  tasks:

    - name: Установите необходимые пакеты
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Убедитесь, что служба Docker запущена
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add deploy user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - debug:
        var: docker_version.stdout

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version

    - debug:
        var: compose_version.stdout
